spring.application.name=lms-system
firebase.service-account-path=${FIREBASE_SERVICE_ACCOUNT_PATH:classpath:service-account.json}

server.port=${PORT:8081}
lms.jwt.secret=${JWT_SECRET:9a67475d45d62557342fb635a8f4679a67475d45d62557342fb635a8f467}
lms.jwt.expirationMs=86400000
